version: '3'
services:
  web:
    build:
      context: .
    container_name: node
    volumes:
      - ./code:/code
    #command: bash -c "npm install && npm start"
    command: bash -c "npm install && npm run dev:server"
    env_file:
      - .env
    ports:
      - "8088:3000"
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

